/**********************************************************************************************************************
 * Scimitar 7 - A tool for parameter-space exploration.
 * Compiler Library Implementation
 *
 * Copyright (c) 2013-2020 Andrew C. Loheac, Joaquin E. Drut, et al.
 * See LICENSE.TXT distributed with the source for for license information.
 *
 *    Python library interface definition.
 *
 *    DESCRIPTION: This file defines the target Python library interface, as provided using the external PYBIND11
 *                 library.
 *
 *    CREATION DATE: November 22, 2019
 *
 *********************************************************************************************************************/

#ifndef SCIMITAR7_PYTHONINTERFACE_H
#define SCIMITAR7_PYTHONINTERFACE_H

#include <pybind11/pybind11.h>
#include "ParserFrontend.h"

/**
 * Compiles a script and returns the emitted Python objects.
 * @param input The input script to compile.
 * @return Python objects (represented as valid Python code) generated by the compiler, including STATUS, RUN_LISTING,
 * DIR_ORDER, and OPTION. If an exception is encountered, STATUS and ERROR_MSG are returned instead.
 */
std::string compile( std::string input );

namespace py = pybind11;

// Define the required objects to produce a Python binding. Refer to the PYBIND11 library documentation for details.
PYBIND11_MODULE( libscimitar, m ) {
    m.doc() = "Scimitar Compiler Interface";
    m.def( "compile", &compile, "Compiles a Scimitar run definition." );
}

#endif //SCIMITAR7_PYTHONINTERFACE_H
